### ISSUE TITLE
Roadmap towards a v1.1.0

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/typology#24]
- [ ] : Probably a partial rewrite of the lib's internals.
- [ ] : More precise errors.
- [ ] : Partial validation through the `~` sigil.
- [ ] : Possibility to pass functions as type as a shortcut (sometimes, you just want a one-time validation and do not want to be bothered by custom types creation).
- [ ] : Adding some ES6-related types.

@jacomyal: sounds good?
